# SITE CONFIGURATION
title: GYULOG # your site title
author: HyunGyu Kim# You :P
description: > 
  Development
baseurl: "" 
url: "https://gusrb3164.github.io/" 

# SEO PLUGIN
social:
  name: HyunGyu Kim
  links:
    - https://github.com/gusrb3164
    - https://www.instagram.com/hyun__9yu
    
# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best prac
  

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: gusrb3164@gmail.com # email for form submission

twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:  gusrb3164# replace with your_github_username or comment to remove link from footer
instagram_username: hyun__9yu# replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: gusrb3164 # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
